<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>AIToolbox.SemanticKernel.Connectors.MistralAI</AssemblyName>
    <RootNamespace>AIToolbox.SemanticKernel</RootNamespace>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <NoWarn>$(NoWarn)</NoWarn>
    <EnablePackageValidation>false</EnablePackageValidation>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SemanticKernel.DependencyInjection\SemanticKernel.DependencyInjection.csproj" />
  </ItemGroup>

  <Import Project="$(RepoRoot)/nuget/NuGet.Package.props" />

  <PropertyGroup>
    <!-- NuGet Package Settings -->
    <Title>AI Toolbox - Semantic Kernel's Mistral AI connector</Title>
    <Description>Semantic Kernel's Mistral AI connector for AI Toolbox.</Description>
  </PropertyGroup>

</Project>
