<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>AIToolbox.Abstractions</AssemblyName>
    <RootNamespace>AIToolbox</RootNamespace>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <NoWarn>$(NoWarn)</NoWarn>
    <EnablePackageValidation>false</EnablePackageValidation>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AIToolbox.DependencyInjection" />
    <InternalsVisibleTo Include="AIToolbox.SemanticKernel.Connectors.AzureOpenAI" />
    <InternalsVisibleTo Include="AIToolbox.SemanticKernel.Connectors.Google" />
    <InternalsVisibleTo Include="AIToolbox.SemanticKernel.Connectors.HuggingFace" />
    <InternalsVisibleTo Include="AIToolbox.SemanticKernel.Connectors.MistralAI" />
    <InternalsVisibleTo Include="AIToolbox.SemanticKernel.Connectors.Ollama" />
    <InternalsVisibleTo Include="AIToolbox.SemanticKernel.Connectors.OpenAI" />
    <InternalsVisibleTo Include="AIToolbox.SemanticKernel.DependencyInjection" />
  </ItemGroup>

  <Import Project="$(RepoRoot)/nuget/NuGet.Package.props" />

  <PropertyGroup>
    <!-- NuGet Package Settings -->
    <Title>AI Toolbox - Abstractions</Title>
    <Description>AI Toolbox interfaces and abstractions. This package is automatically installed by AI Toolbox packages if needed.</Description>
  </PropertyGroup>

</Project>
